-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#1d1013",
	base01 = "#170b0d",
	base02 = "#26181b",
	base03 = "#5b3f45",
	base04 = "#e4bdc4",
	base05 = "#f6dce0",
	base06 = "#3c2c2f",
	base07 = "#463538",

	base08 = "#ffb4ab",
	base09 = "#ffb1c2",
	base0A = "#dfb8f6",
	base0B = "#e2b5ff",
	base0C = "#713344",
	base0D = "#5f3280",
	base0E = "#593a6e",
	base0F = "#93000a",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#5f3280",
	fg = "#1d1013",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#ffd9e0",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#ffb1c2",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#dfb8f6",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#794a9a",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#170b0d",
	fg = "#e2b5ff",
})
